pipeline 
{
    agent {
        slave1
    }
    stages {

        stage('Build') {

            steps {
withMaven(jdk: 'JAVA', maven: 'maven') 
             {
bat'mvn clean compile'
}
            }
        }
                   
            }
            
}
