pipeline 
{
    agent {
    node {
        label 'my-defined-label'
        customWorkspace '/some/other/path'
    }
    }
    stages {

        stage('Build') {

            steps {
withMaven(jdk: 'JAVA', maven: 'maven') 
             {
bat'mvn clean compile'
}
            }
        }
                   
            }
            
}
